// src/Options/index.vue
<template>
	<div v-if="loading" class="spinner-grow inline-block w-12 h-12 bg-current rounded-full opacity-0" role="status">
		<span class="visually-hidden">Loading...</span>
	</div>
	<div v-if="!loading" class="body">
		<Services :loading="loading" />
	</div>
	<div class="pt-4"></div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Options } from "@Core/Options";
import Services from "./Components/Services.vue";

const loading = ref(true);

onMounted(async () => {
	await Options.load();
	loading.value = false;
});
</script>

<style lang="css"></style>

// src/Options/index.svelte
<script lang="ts">
	import Services from "./lib/Services.svelte";
	import Options from "./lib/Options.svelte";
	import { loading, optionsStore } from "./stores/Options";

	optionsStore.load();
</script>

<main>
	{#if $loading}
		<div class="spinner-grow inline-block w-12 h-12 bg-current rounded-full opacity-0" role="status">
			<span class="visually-hidden">Loading...</span>
		</div>
	{:else}
		<div class="body">
			<Services />
			<Options />
		</div>
	{/if}
	<div class="pt-4" />
</main>
