// src/Options/lib/ServiceCard.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { tabs } from "webextension-polyfill";
	import { Lake } from "@Core/Lake";
	import { file } from "@Core/Utility";
	import { loginResultMap, loginStatusMap, ServiceLogin, ServiceStatus } from "@Core/Service";
	import { optionsStore } from "../stores/Options";
	import Button from "@Components/Button.svelte";
	import Badge from "@Components/Badge.svelte";
	import Modal from "@Components/Modal.svelte";
	import Alert from "@Components/Alert.svelte";

	export let serviceKey: string;

	let loading = false;
	const service = Lake.services.find((service) => service.key === serviceKey)!;
	$: isActive = $optionsStore ? $optionsStore.services.includes(serviceKey) : false;

	let modal: Modal;

	let cardClasses = "service-card";
	let cardStyle = "";
	let status: ServiceStatus = ServiceStatus.LOADING;
	let loggedUser: string | undefined;
	if (service) {
		if (service.theme?.color) {
			cardStyle = `border-color: ${service.theme.color}; color: ${service.theme.color};`;
		} else {
			cardClasses = `${cardClasses} border-tachikoma-500`;
		}
		if (service.theme?.background) {
			cardStyle = `${cardStyle} background-color: ${service.theme.background};`;
		} else {
			cardClasses = `${cardClasses} bg-tachikoma-600`;
		}
	}

	// Management functions

	async function loadStatus() {
		status = ServiceStatus.LOADING;
		loggedUser = undefined;
		if (isActive) {
			const serviceStatus = await service.status();
			status = serviceStatus.status;
			loggedUser = serviceStatus.user;
		}
	}

	let loginResult: { status: ServiceLogin; message?: string } | null = null;
	async function loginOrRedirect() {
		loginResult = null;
		loading = true;
		if (service.loginRedirect) {
			const redirectUrl = await service.loginRedirect();
			await tabs.create({ url: redirectUrl, active: true });
		} else {
			modal.show();
		}
		loading = false;
	}

	let loginInformations: ServiceLoginInformations = {};
	let loggingIn = false;
	async function sendLoginInformations() {
		loggingIn = true;
		loginResult = { status: ServiceLogin.LOADING };
		if ("login" in service) {
			loginResult = await service.login(loginInformations);
			if (loginResult.status === ServiceLogin.SUCCESS) {
				loadStatus();
				modal.hide();
			}
		}
		loggingIn = false;
	}

	async function logout() {
		loading = true;
		if ("logout" in service && service.logout) {
			await service.logout();
		}
		await service.storage.clear();
		await loadStatus();
		loading = false;
	}

	async function activateServiceAndSave() {
		loading = true;
		optionsStore.activateService(serviceKey);
		await optionsStore.save();
		loading = false;
	}

	async function deactivateServiceAndSave() {
		loading = true;
		await logout();
		optionsStore.deactivateService(serviceKey);
		await optionsStore.save();
		loading = false;
	}

	async function moveUpAndSave() {
		loading = true;
		optionsStore.moveServiceUp(serviceKey);
		await optionsStore.save();
		loading = false;
	}

	async function moveDownAndSave() {
		loading = true;
		optionsStore.moveServiceDown(serviceKey);
		await optionsStore.save();
		loading = false;
	}

	//

	$: canLogin = status !== ServiceStatus.LOGGED_IN && status !== ServiceStatus.SERVICE_ERROR;
	$: canLogout =
		status !== ServiceStatus.MISSING_COOKIES && status !== ServiceStatus.MISSING_TOKEN && "logout" in service;
	$: isFirst = $optionsStore?.services.indexOf(serviceKey) === 0;
	$: isLast =
		$optionsStore !== null && $optionsStore.services.indexOf(serviceKey) === $optionsStore.services.length - 1;

	// Maps

	const statusMap: {
		description: { [key in ServiceStatus]: string };
		color: { [key in ServiceStatus]: "loading" | "success" | "error" | "warning" | "info" };
	} = {
		description: loginStatusMap,
		color: {
			[ServiceStatus.MISSING_TOKEN]: "warning",
			[ServiceStatus.MISSING_COOKIES]: "warning",
			[ServiceStatus.INVALID_TOKEN]: "warning",
			[ServiceStatus.SERVICE_ERROR]: "error",
			[ServiceStatus.TACHIKOMA_ERROR]: "warning",
			[ServiceStatus.LOADING]: "info",
			[ServiceStatus.LOGGED_IN]: "success",
		},
	};

	const loginMap: {
		description: { [key in ServiceLogin]: string };
		color: { [key in ServiceLogin]: "loading" | "success" | "error" | "warning" | "info" };
	} = {
		description: loginResultMap,
		color: {
			[ServiceLogin.MISSING_FIELDS]: "warning",
			[ServiceLogin.EXPIRED_CHALLENGE]: "warning",
			[ServiceLogin.INVALID_CREDENTIALS]: "error",
			[ServiceLogin.INVALID_CHALLENGE]: "error",
			[ServiceLogin.SERVICE_ERROR]: "error",
			[ServiceLogin.TACHIKOMA_ERROR]: "warning",
			[ServiceLogin.LOADING]: "info",
			[ServiceLogin.SUCCESS]: "success",
		},
	};

	//

	onMount(() => {
		loadStatus();
	});
</script>

{#if service}
	<div class={cardClasses} style={cardStyle}>
		<div class="icon flex-grow-0 flex-shrink-0 mr-4">
			<img src={file(`/static/icons/${service.key}.png`)} alt={`${service.name} icon`} />
		</div>
		<div class="name-status flex flex-col flex-grow flex-shrink text-ellipsis">
			{#if service.theme?.title}
				<div class="name text-xl font-bold">{@html service.theme.title().innerHTML}</div>
			{:else}
				<div class="name text-xl font-bold">{service.name}</div>
			{/if}
			{#if isActive}
				<div class="status mt-1">
					<Badge type={statusMap.color[status]}>{statusMap.description[status]}</Badge>
				</div>
				{#if loggedUser}
					<div class="mt-1 ">
						<Badge type="info">{loggedUser}</Badge>
					</div>
				{/if}
			{/if}
		</div>
		<div class="actions flex flex-row flex-grow-0 flex-shrink-0 items-center">
			<div class="main-action">
				{#if !isActive}
					<Button type="success" disabled={loading} on:click={activateServiceAndSave}>Activate</Button>
				{:else if status != ServiceStatus.LOADING}
					{#if canLogin}
						{#if service.loginRedirect}
							<Button type="success" on:click={loginOrRedirect}>
								<span>Login</span>
								<i class="light-icon-external-link text-lg ml-2" />
							</Button>
						{:else}
							<Button type="success" on:click={loginOrRedirect}>
								<span>Login</span>
								<i class="light-icon-login text-lg ml-2" />
							</Button>
							<Modal bind:this={modal} let:hide>
								<span slot="header">Login</span>
								<div slot="default">
									{#if !service.loginInformations}
										Missing login informations !
									{:else}
										{#each service.loginInformations as field (field.name)}
											<!-- ? `'type' attribute cannot be dynamic if input uses two-way binding`  -->
											{#if field.type == "password"}
												<input
													bind:value={loginInformations[field.name]}
													class="input"
													type="password"
													name={field.name}
													placeholder={field.label}
													required={field.required}
												/>
											{:else if field.type == "email"}
												<input
													bind:value={loginInformations[field.name]}
													class="input"
													type="email"
													name={field.name}
													placeholder={field.label}
													required={field.required}
												/>
											{:else}
												<input
													bind:value={loginInformations[field.name]}
													class="input"
													type="text"
													name={field.name}
													placeholder={field.label}
													required={field.required}
												/>
											{/if}
										{/each}
									{/if}
									{#if loginResult && loginResult.status !== ServiceLogin.SUCCESS}
										<Alert type={loginMap.color[loginResult.status]}>
											{loginMap.description[loginResult.status]}
										</Alert>
									{/if}
								</div>
								<div slot="footer">
									<Button
										type="success"
										disabled={loggingIn}
										class="mr-2"
										on:click={sendLoginInformations}
									>
										<span>Login</span>
										<i class="light-icon-login text-lg ml-2" />
									</Button>
									<Button type="warning" disabled={loggingIn} on:click={hide}>Close</Button>
								</div>
							</Modal>
						{/if}
					{/if}
					{#if canLogout}
						<Button type="info" class="ml-2" on:click={logout}>
							<span>Logout</span>
							<i class="light-icon-logout text-lg ml-2" />
						</Button>
					{/if}
				{/if}
				{#if isActive}
					<Button type="error" class="ml-2" disabled={loading} on:click={deactivateServiceAndSave}>
						Deactivate
					</Button>
				{/if}
			</div>
			{#if isActive}
				<div class="sub-actions flex flex-col ml-4">
					<Button type="info" size="sm" class="mb-2" disabled={isFirst} on:click={moveUpAndSave}>
						<i class="light-icon-chevron-up text-lg" />
					</Button>
					<Button type="info" size="sm" disabled={isLast} on:click={moveDownAndSave}>
						<i class="light-icon-chevron-down text-lg" />
					</Button>
				</div>
			{/if}
		</div>
	</div>
{:else}
	<div class={cardClasses} style={cardStyle}>Invalid service</div>
{/if}

<style lang="postcss">
	.service-card {
		@apply m-4 px-4 py-2 flex flex-row items-center rounded-md border shadow-md;
	}
	.service-card:last-child {
		@apply mb-0;
	}
	.input {
		@apply block w-full px-3 py-1.5 mb-2 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none;
	}
	.input:last-child {
		@apply mb-0;
	}
</style>

// src/Options/Components/ServiceCard.vue
<template>
	<div class="service-card" :class="cardClasses" :style="cardStyle">
		<div class="icon flex-grow-0 flex-shrink-0 mr-4">
			<img :src="filePath(`/icons/${service.key}.png`)" :alt="`${service.name} icon`" />
		</div>
		<div class="name-status flex flex-col flex-grow flex-shrink text-ellipsis">
			<div
				v-if="service.theme?.title"
				class="name text-xl font-bold"
				v-html="service.theme.title().innerHTML"
			></div>
			<div v-else class="name text-xl font-bold">{{ service.name }}</div>
			<div v-if="isActive" class="status mt-1">
				<Badge :type="statusMap.color[status]">{{ statusMap.description[status] }}</Badge>
			</div>
		</div>
		<div class="actions flex flex-row flex-grow-0 flex-shrink-0 items-center">
			<div class="main-action">
				<Button v-if="!isActive" type="success" @click="activateServiceAndSave">Activate</Button>
				<template v-else-if="status != ServiceStatus.LOADING">
					<template v-if="canLogin">
						<Button v-if="service.loginRedirect" type="success" @click="loginOrRedirect">
							<span>Login</span>
							<i class="light-icon-external-link text-lg ml-2"></i>
						</Button>
						<template v-else>
							<Button type="success" @click="loginOrRedirect">
								<span>Login</span>
								<i class="light-icon-login text-lg ml-2"></i>
							</Button>
							<Modal v-model="loginModalVisible">
								<template #header>Login</template>
								<template #default>
									<template v-if="!service.loginInformations">
										Missing login informations !
									</template>
									<template v-else>
										<input
											v-for="field in service.loginInformations"
											:key="`password-${field.name}`"
											v-model="loginInformations[field.name]"
											class="input"
											:type="field.type"
											:name="field.name"
											:placeholder="field.label"
											:required="field.required"
										/>
									</template>
									<Alert
										v-if="loginResult && loginResult.status !== ServiceLogin.SUCCESS"
										:type="loginMap.color[loginResult.status]"
									>
										{{ loginMap.description[loginResult.status] }}
									</Alert>
								</template>
								<template #footer="{ hide }">
									<Button
										type="success"
										:disabled="loggingIn"
										class="mr-2"
										@click="sendLoginInformations"
									>
										<span>Login</span>
										<i class="light-icon-login text-lg ml-2"></i>
									</Button>
									<Button type="warning" :disabled="loggingIn" @click="hide">Close</Button>
								</template>
							</Modal>
						</template>
					</template>
					<Button v-if="canLogout" type="info" class="ml-2" @click="logout">
						<span>Logout</span>
						<i class="light-icon-logout text-lg ml-2"></i>
					</Button>
					<Button type="error" class="ml-2" @click="deactivateServiceAndSave">Deactivate</Button>
				</template>
			</div>
			<div v-if="isActive" class="sub-actions flex flex-col ml-4">
				<Button type="info" size="sm" class="mb-2" :disabled="index(service.key) == 0" @click="moveUpAndSave">
					<i class="light-icon-chevron-up text-lg"></i>
				</Button>
				<Button type="info" size="sm" :disabled="isLast(service.key)" @click="moveDownAndSave">
					<i class="light-icon-chevron-down text-lg"></i>
				</Button>
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import { windows, tabs } from "webextension-polyfill";
import { ref, computed } from "@vue/reactivity";
import { file } from "@Core/Utility";
import { AnyService, ServiceStatus, ServiceLogin } from "@Core/Service";
import Button from "./Button.vue";
import Badge from "./Badge.vue";
import Modal from "./Modal.vue";
import Alert from "./Alert.vue";
import { useOptions } from "../Hooks/Options";
import { useService } from "../Hooks/Service";

const props = defineProps<{ service: AnyService }>();

// * Style

const cardClasses: string[] = [];
const cardStyle: { borderColor: string | undefined; backgroundColor: string | undefined; color: string | undefined } = {
	borderColor: undefined,
	backgroundColor: undefined,
	color: undefined,
};
if (props.service.theme?.color) {
	cardStyle.borderColor = props.service.theme.color;
	cardStyle.color = props.service.theme.color;
} else cardClasses.push("border-tachikoma-500");
if (props.service.theme?.background) {
	cardStyle.backgroundColor = props.service.theme.background;
} else cardClasses.push("bg-tachikoma-600");

//

const { services, save } = useOptions();
const { status: statusMap, login: loginMap } = useService();
const status = ref<ServiceStatus>(ServiceStatus.LOADING);
const loginModalVisible = ref(false);
const loginInformations = ref<ServiceLoginInformations>({});
const loginResult = ref<{ status: ServiceLogin; message?: string } | null>(null);
const loggingIn = ref(false);

const canLogin = computed(() => {
	return status.value !== ServiceStatus.LOGGED_IN && status.value !== ServiceStatus.SERVICE_ERROR;
});
const canLogout = computed(() => {
	return (
		status.value !== ServiceStatus.MISSING_COOKIES &&
		status.value !== ServiceStatus.MISSING_TOKEN &&
		"logout" in props.service
	);
});

const isActive = computed(() => {
	return services.has(props.service.key);
});
const index = services.index;
const isLast = services.isLast;

const loading = ref(false);
const activateServiceAndSave = async () => {
	loading.value = true;
	services.activate(props.service.key);
	await save();
	loading.value = false;
};
const deactivateServiceAndSave = async () => {
	loading.value = true;
	services.deactivate(props.service.key);
	await save();
	loading.value = false;
};

async function closeSelf() {
	const { id: windowId } = await windows.getCurrent();
	if (windowId) return windows.remove(windowId);
}

const loginOrRedirect = async () => {
	loginResult.value = null;
	loading.value = true;
	if (props.service.loginRedirect) {
		const redirectUrl = await props.service.loginRedirect();
		// const link = document.createElement("a");
		// link.style.display = "none";
		// link.href = redirectUrl;
		// link.target = "_blank";
		// link.rel = "noreferrer noopener";
		// document.body.appendChild(link);
		// link.click();
		// link.remove();
		await tabs.create({ url: redirectUrl, active: true });
		// closeSelf();
	} else {
		loginModalVisible.value = true;
	}
	loading.value = false;
};
const sendLoginInformations = async () => {
	loggingIn.value = true;
	loginResult.value = { status: ServiceLogin.LOADING };
	if ("login" in props.service) {
		loginResult.value = await props.service.login(loginInformations.value);
		if (loginResult.value.status === ServiceLogin.SUCCESS) {
			loadStatus();
			loginModalVisible.value = false;
		}
	}
	loggingIn.value = false;
};
const logout = async () => {
	loading.value = true;
	if ("logout" in props.service && props.service.logout) {
		await props.service.logout();
	}
	await props.service.storage.clear();
	await loadStatus();
	loading.value = false;
};

const moveUpAndSave = async () => {
	loading.value = true;
	services.moveUp(props.service.key);
	await save();
	loading.value = false;
};
const moveDownAndSave = async () => {
	loading.value = true;
	services.moveDown(props.service.key);
	await save();
	loading.value = false;
};

const loadStatus = async () => {
	if (isActive) {
		const serviceStatus = await props.service.status();
		status.value = serviceStatus.status;
	}
};
onMounted(loadStatus);

const filePath = (path: string) => {
	return file(path);
};
</script>

<style scoped>
.service-card {
	@apply m-4 px-4 py-2 flex flex-row items-center rounded-md border shadow-md;
}
.service-card:last-child {
	@apply mb-0;
}
.input {
	@apply block w-full px-3 py-1.5 mb-2 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none;
}
.input:last-child {
	@apply mb-0;
}
</style>
