// src/Options/lib/Services.svelte
<script lang="ts">
	import { optionsStore } from "../stores/Options";
	import Title from "./Title.svelte";
	import ServiceCard from "./ServiceCard.svelte";
	import { Lake } from "@Core/Lake";

	$: activeServices = $optionsStore ? $optionsStore.services : [];
	$: inactiveServices = Lake.services
		.filter((service) => !activeServices.includes(service.key))
		.map((service) => service.key);
</script>

<Title size="1">Services</Title>
<Title size="2">
	Active <span>({activeServices.length})</span>
</Title>
<div>
	{#each activeServices as serviceKey (serviceKey)}
		<ServiceCard {serviceKey} />
	{/each}
</div>
<Title size="2">
	Inactive <span>({inactiveServices.length})</span>
</Title>
<div>
	{#each inactiveServices as serviceKey (serviceKey)}
		<ServiceCard {serviceKey} />
	{/each}
</div>

// src/Options/Components/Services.vue
<template>
	<div>
		<Title size="1">Services</Title>
		<Title size="2">
			Active <span v-if="!loading"> ({{ activeServices.length }}) </span>
		</Title>
		<div>
			<ServiceCard v-for="service in activeServices" :key="`active-${service.key}`" :service="service" />
		</div>
		<Title size="2">
			Inactive <span v-if="!loading"> ({{ inactiveServices.length }}) </span>
		</Title>
		<div>
			<ServiceCard v-for="service in inactiveServices" :key="`inactive-${service.key}`" :service="service" />
		</div>
	</div>
</template>

<script setup lang="ts">
import { Lake } from "@Core/Lake";
import Title from "./Title.vue";
import { ref, watch } from "vue";
import Service from "@Core/Service";
import ServiceCard from "./ServiceCard.vue";

const props = defineProps<{ loading: boolean }>();

const activeServices = ref<Service[]>([]);
const inactiveServices = ref<Service[]>([]);

watch(
	() => props.loading,
	() => {
		activeServices.value = Lake.active();
		inactiveServices.value = Lake.inactive();
	}
);
</script>

<style></style>
